from pathlib import Path
from typing import IO, Any

from fast_ebook import EpubItem, TocEntry

class EpubHtml:
    id: str
    title: str
    file_name: str
    lang: str | None
    media_type: str
    content: bytes
    def __init__(
        self,
        uid: str | None = ...,
        title: str = ...,
        file_name: str = ...,
        lang: str | None = ...,
        content: bytes | str = ...,
        media_type: str = ...,
    ) -> None: ...
    def get_content(self) -> bytes: ...
    def get_type(self) -> int: ...
    def get_name(self) -> str: ...
    def get_id(self) -> str: ...

class EpubImage:
    id: str
    file_name: str
    media_type: str
    content: bytes
    def __init__(
        self,
        uid: str | None = ...,
        file_name: str = ...,
        media_type: str = ...,
        content: bytes = ...,
    ) -> None: ...
    def get_type(self) -> int: ...
    def get_name(self) -> str: ...
    def get_id(self) -> str: ...
    def get_content(self) -> bytes: ...

class EpubCss:
    id: str
    file_name: str
    media_type: str
    content: bytes
    def __init__(
        self,
        uid: str | None = ...,
        file_name: str = ...,
        content: bytes | str = ...,
    ) -> None: ...
    def get_type(self) -> int: ...
    def get_name(self) -> str: ...
    def get_id(self) -> str: ...
    def get_content(self) -> bytes: ...

class EpubNcx:
    id: str
    file_name: str
    media_type: str
    content: bytes
    def __init__(self) -> None: ...
    def get_type(self) -> int: ...

class EpubNav:
    id: str
    file_name: str
    media_type: str
    content: bytes
    def __init__(self) -> None: ...
    def get_type(self) -> int: ...

class Link:
    href: str
    title: str
    uid: str
    def __init__(self, href: str, title: str, uid: str = ...) -> None: ...

class Section:
    title: str
    def __init__(self, title: str) -> None: ...

class EpubBook:
    toc: list[TocEntry | Link | tuple[Section, list[Any]]]
    spine: list[str | EpubHtml | tuple[str, bool]]
    def __init__(self) -> None: ...
    def __enter__(self) -> EpubBook: ...
    def __exit__(self, *args: Any) -> None: ...
    def set_identifier(self, identifier: str) -> None: ...
    def set_title(self, title: str) -> None: ...
    def set_language(self, lang: str) -> None: ...
    def add_author(
        self,
        name: str,
        file_as: str | None = ...,
        role: str | None = ...,
        uid: str | None = ...,
    ) -> None: ...
    def add_metadata(
        self,
        namespace: str,
        name: str,
        value: str,
        others: dict[str, str] | None = ...,
    ) -> None: ...
    def add_item(
        self, item: EpubHtml | EpubImage | EpubCss | EpubNcx | EpubNav
    ) -> None: ...
    def set_cover(self, file_name: str, content: bytes) -> None: ...
    def get_items(self) -> list[EpubItem]: ...
    def get_items_of_type(self, item_type: int) -> list[EpubItem]: ...
    def get_item_with_id(self, item_id: str) -> EpubItem | None: ...
    def get_item_with_href(self, href: str) -> EpubItem | None: ...
    def get_metadata(
        self, namespace: str, name: str
    ) -> list[tuple[str, dict[str, str]]]: ...
    def get_spine(self) -> list[tuple[str, bool]]: ...
    def validate(self) -> list[str]: ...
    def __repr__(self) -> str: ...

def read_epub(
    source: str | Path | bytes | IO[bytes],
    options: dict[str, Any] | None = ...,
) -> EpubBook: ...
def write_epub(
    target: str | Path | IO[bytes], book: EpubBook
) -> None: ...
def read_epubs(
    paths: list[str | Path],
    workers: int | None = ...,
    options: dict[str, Any] | None = ...,
) -> list[EpubBook]: ...
def open(
    source: str | Path | bytes | IO[bytes],
    options: dict[str, Any] | None = ...,
) -> EpubBook: ...
